### ISSUE TITLE
Add Jupyter Desktop

### ISSUE THREAD

**Issue by tannerlegvold** [markusschanta/awesome-jupyter#126]
Add [Jupyter Desktop](https://github.com/jupyterlab/jupyterlab-desktop) in the Runtimes/Frontends section.

**Comment by markusschanta** [comment]
Hi @tannerlegvold ! Thank you for the suggestion. I just added Jupyterlab Desktop in #138.

Sorry, this fell through the cracks. I didn't notice it because it was opened as an Issue rather than a PR. Anyway, it's on the list now. All's well that ends well. 😊
