### ISSUE TITLE
jupyter-viewer-xblock

### ISSUE THREAD

**Issue by westurner** [markusschanta/awesome-jupyter#18]
https://github.com/ibleducation/jupyter-viewer-xblock

> View Jupyter Notebooks in Open edX - https://ibleducation.com/jupyter-viewer-xblock

https://github.com/ibleducation/jupyter-viewer-xblock

**Comment by markusschanta** [comment]
Thanks again @westurner. Added this in ef98f5b21e7140ae7408c869a8b8948b65bf94f5.

**Comment by westurner** [comment]
Thanks!

You can add e.g. "closes #18' or 'fixes #18' in the commit message to
automatically close the issue and add a trackback to the commit.

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by markusschanta** [comment]
Cool, I thought that there was probably some trickery to do something like that. Good to know how it works!

BTW: I've opened a [PR](https://github.com/sindresorhus/awesome/pull/1160) to get this included in [awesome](https://github.com/sindresorhus/awesome/) (ie. the "root" list). Would be great if you can upvote it/weigh in. Thanks!
