### ISSUE TITLE
GitHub topic links

### ISSUE THREAD

**Issue by westurner** [markusschanta/awesome-jupyter#8]
https://github.com/quobit/awesome-python-in-education#jupyter

https://github.com/postpdm/awesome-jupyter

**Comment by westurner** [comment]
https://github.com/postpdm/awesome-jupyter/issues/2

**Comment by adebar** [comment]
Thanks, @westurner. I'll work these into the list.

**Comment by adebar** [comment]
Had a look at the lists, there are some really good suggestions in there. There are also a couple of things that are deprecated (since Jupyterlab). Need to sort through the list properly. Was thinking of putting everything that doesn't make the cut into a separate list (call it the "less awesome list") and put it in the repo as well. That way it can serve as a reference for everything that has been suggested already and didn't make the cut and why.

**Comment by westurner** [comment]
Maybe a "Testing" or "Test Driven Development" heading?

- py.test
  - https://github.com/computationalmodelling/nbval
- nose
  - https://github.com/taavi/ipython_nose
  - https://github.com/bollwyvl/nosebook

Other things

- runipy is now possible with just ``jupyter convert``
  https://pypi.python.org/pypi/runipy
  https://github.com/paulgb/runipy

  https://nbconvert.readthedocs.io/en/latest/execute_api.html#executing-notebooks-from-the-command-line

- ipython/ipynb allows importing code from notebooks (but isn't as fast as a well-refactored, tested, packaged module)
  https://github.com/ipython/ipynb
  https://pypi.org/project/ipynb/

- nbdime - visual diff tool for Jupyter notebooks
  https://nbdime.readthedocs.io/en/stable/

  (works as a merge driver and a diff driver)
  https://nbdime.readthedocs.io/en/stable/vcs.html#git-integration

**Comment by markusschanta** [comment]
@westurner, I collected all the individual resources under those links (~100 projects) and sorted them into awesome/not awesome/duplicate. You can see what I've been up to on the [westurner-suggestions branch](https://github.com/markusschanta/awesome-jupyter/compare/master...westurner-suggestions). I'll weave the remaining projects into the existing lists in the next couple of days.

**Comment by westurner** [comment]
:+1: Thanks!

**Comment by markusschanta** [comment]
@westurner Just finished sorting all the projects into categories. I went ahead and merged the branch. Thanks again for the suggestions! In total I added around 40 or so new projects to the list, the biggest step forward so far!

**Comment by westurner** [comment]
There are also GitHub topic links for Ipython, Jupyter, Jupyterlab:

https://github.com/topics/ipython
https://github.com/topics/jupyter
https://github.com/topics/jupyter-notrbook
https://github.com/topics/jupyterhub
https://github.com/topics/jupyterlab
https://github.com/topics/jupyterlab-extension

There are also PyPI trove classifiers that would be great to add to projects' metadata in the project metadata in setup.py:

https://github.com/pypa/pypi-legacy/issues/210
https://github.com/Carreau/warehouse/commit/3f465459158b1a34469c2bf521006f7fc48dbfbc
``Framework :: Jupyter``
